### ISSUE TITLE
Photopress gallery not appearing in block options.

### ISSUE THREAD

**Issue by SLew11** [photopress-dev/photopress-plugin#10]
I have installed the Photopress plugin successfully but when trying to add a Photopress gallery to a new page, there are no PhotoPress gallery options appearing in the new block options.

It's a clean installation of Wordpress 5.6 with the default theme Twenty Twenty One and no other plugins. It's an nginx, MySQL 8.0.16 on a "Local" installation on a Mac BigSur. Other plugins do work ok.

**Comment by padams** [comment]
Does the media selector area show at the bottom of the block?

**Comment by SLew11** [comment]
When adding a new block to a page in the Media selector area the only options are the standard WP options such as Image and Gallery etc.

**Comment by padams** [comment]
After you add a PhotoPress gallery block to a page there will be a media selector button that appears where you inserted the block. Use that to choose images and then the block options will appear.

**Comment by SLew11** [comment]
How do I create a PhotoPress gallery? I can’t see that function anywhere on the site.
Under the PhotoPress admin option I can see 2 tabs, one for Slideshow and one for Meta-data. Where is the option to create a PhotoPress gallery?

Thanks.

**Comment by padams** [comment]
The plug-in adds a block type called PhotoPress gallery. Scroll or search through the block options to find it.

**Comment by SLew11** [comment]
Im afraid I cannot see the PhotoPress gallery block type and it’s not found if I try to search for it. Sorry.

**Comment by padams** [comment]
Is the plug-in activated?

**Comment by SLew11** [comment]
Yes it is. I’ve just deactivated and then reactivated the plugin with no joy.
As I said, under the PhotoPress admin option I can see 2 tabs, one for Slideshow and one for Meta-data. 
Plus under the Media admin are the Cameras, Lenses etc options.

**Comment by padams** [comment]
That is correct but those menus don't affect galleries. They are added via the block editor of the page or post where you want to add the gallery.

Did you search through the available blocks to add?

**Comment by SLew11** [comment]
I assume that those menus do indicate that the plugin is active, as well as appearing as active in the Plugin admin tabs.

No, the PhotoPress gallery does not appear in the block options nor does it appear if I try to use the search option.

**Comment by padams** [comment]
Figure out what was happening. This is now fixed in the latest release.

**Comment by SLew11** [comment]
Thank you.

Regards,

Stephen
