### ISSUE TITLE
Uncaught ReferenceError: photopress is not defined

### ISSUE THREAD

**Issue by taliesinpenbardd** [photopress-dev/photopress-plugin#2]
Hey all,
Wonderful idea, this plugin!
However, I get a JS error in the console, who says:
```
Uncaught ReferenceError: photopress is not defined
    <anonymous> http://stulamu.test/wp-content/plugins/photopress/modules/slideshow/assets/js/slideshow.js:10
```
Using DebugPress, I can see the "photopress-slideshow" and "photopress-masonry" scripts are presented BEFORE the "photopress" script, but that could also be a quirk in the DebugPress presentation. 

**Environment:** 
Valet (MacOS), PHP 7.4
WP 5.5.1
Photopress 1.4.0
Gallery is in "Justified" mode

**Comment by padams** [comment]
Nice catch on these. thanks.
